//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SharedClass.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AccountResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AccountResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SharedClass.Resources.AccountResource", typeof(AccountResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Password.
        /// </summary>
        public static string btn_ResetPswd {
            get {
                return ResourceManager.GetString("btn_ResetPswd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to delete this record?.
        /// </summary>
        public static string Confirm_delete {
            get {
                return ResourceManager.GetString("Confirm_delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was a database level error while attempting to save this user. Please contact the administrator if this error persists..
        /// </summary>
        public static string criticalError {
            get {
                return ResourceManager.GetString("criticalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forum Research.
        /// </summary>
        public static string displayName {
            get {
                return ResourceManager.GetString("displayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Loading Change Password page.
        /// </summary>
        public static string err_LoadChangePswd {
            get {
                return ResourceManager.GetString("err_LoadChangePswd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Loading Reset password page.
        /// </summary>
        public static string err_LoadResetPswd {
            get {
                return ResourceManager.GetString("err_LoadResetPswd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Is Reset Password Time Valid.
        /// </summary>
        public static string err_PswdResetTime {
            get {
                return ResourceManager.GetString("err_PswdResetTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Sending reset password mail.
        /// </summary>
        public static string err_SendResetMail {
            get {
                return ResourceManager.GetString("err_SendResetMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while change and update password.
        /// </summary>
        public static string err_UpdatePswd {
            get {
                return ResourceManager.GetString("err_UpdatePswd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was a database level error while attempting to save this user. Please contact the administrator if this error persists..
        /// </summary>
        public static string Error_DatabaseLevel {
            get {
                return ResourceManager.GetString("Error_DatabaseLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error trying to validate the email address. Please try again..
        /// </summary>
        public static string Error_DBEmailValidationError {
            get {
                return ResourceManager.GetString("Error_DBEmailValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This email address is already used for another user. Please use a unique email address..
        /// </summary>
        public static string Error_EmailInUse {
            get {
                return ResourceManager.GetString("Error_EmailInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid email address..
        /// </summary>
        public static string Error_InvalidEmail {
            get {
                return ResourceManager.GetString("Error_InvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email must be between 4 and 150 characters..
        /// </summary>
        public static string Error_InvalidEmailLength {
            get {
                return ResourceManager.GetString("Error_InvalidEmailLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid user information..
        /// </summary>
        public static string Error_InvalidUser {
            get {
                return ResourceManager.GetString("Error_InvalidUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid user specified. Unable to change password..
        /// </summary>
        public static string Error_InvalidUserCantChangePassword {
            get {
                return ResourceManager.GetString("Error_InvalidUserCantChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No password was entered..
        /// </summary>
        public static string Error_NoPasswordSpecified {
            get {
                return ResourceManager.GetString("Error_NoPasswordSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No username was specified..
        /// </summary>
        public static string Error_NoUsernameSpecified {
            get {
                return ResourceManager.GetString("Error_NoUsernameSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must be between 6 and 20 characters in length..
        /// </summary>
        public static string Error_PasswordLengthNotMet {
            get {
                return ResourceManager.GetString("Error_PasswordLengthNotMet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password complexity requirements not met. Password must have at least one uppercase letter, one lowercase letter and one number..
        /// </summary>
        public static string Error_PasswordNotComplex {
            get {
                return ResourceManager.GetString("Error_PasswordNotComplex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is not a valid user to change password.
        /// </summary>
        public static string error_PswdChange {
            get {
                return ResourceManager.GetString("error_PswdChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to add the user. Something went wrong when connecting to the database. Please try again. (EUA100).
        /// </summary>
        public static string Error_UnableToSaveUser {
            get {
                return ResourceManager.GetString("Error_UnableToSaveUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to update the user. Something went wrong when connecting to the database. Please try again. (EUA100).
        /// </summary>
        public static string Error_UnableToUpdateUser {
            get {
                return ResourceManager.GetString("Error_UnableToUpdateUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not a valid user.Please contact Administrator.
        /// </summary>
        public static string error_User {
            get {
                return ResourceManager.GetString("error_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rgeorge@forumresearch.com.
        /// </summary>
        public static string fromAddress {
            get {
                return ResourceManager.GetString("fromAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter a new password.
        /// </summary>
        public static string Instruction_EnterPassword {
            get {
                return ResourceManager.GetString("Instruction_EnterPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords must be between 6 and 20 characters with at least one upper case letter, one lower case letter and one number..
        /// </summary>
        public static string Instruction_PasswordRequirements {
            get {
                return ResourceManager.GetString("Instruction_PasswordRequirements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We are sorry. We could not find the user associated with this account or the link is invalid. Please try again..
        /// </summary>
        public static string invalidUser {
            get {
                return ResourceManager.GetString("invalidUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        public static string lbl_Confirm {
            get {
                return ResourceManager.GetString("lbl_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password.
        /// </summary>
        public static string lbl_NewPswd {
            get {
                return ResourceManager.GetString("lbl_NewPswd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Password.
        /// </summary>
        public static string lbl_ResetPassword {
            get {
                return ResourceManager.GetString("lbl_ResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We have received your request to reset your password for the TARION ANALYTICS PORTAL. To complete this request, simply click on the following link or paste it into your browser to reset your password.
        ///
        ///{0}
        ///Note: This link will only be active for 12 hours.
        ///
        ///Regards,
        ///TARION ANALYTICS.
        /// </summary>
        public static string mailContent {
            get {
                return ResourceManager.GetString("mailContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tarion Forum Password Recovery.
        /// </summary>
        public static string mailSubject {
            get {
                return ResourceManager.GetString("mailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully added the user..
        /// </summary>
        public static string Message_AddSuccess {
            get {
                return ResourceManager.GetString("Message_AddSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully updated the user..
        /// </summary>
        public static string Message_UpdateSuccess {
            get {
                return ResourceManager.GetString("Message_UpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to These new passwords do not match..
        /// </summary>
        public static string passwordMismatch {
            get {
                return ResourceManager.GetString("passwordMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you have forgotten your password, please enter your email below.
        /// </summary>
        public static string resetPasswordInstructions {
            get {
                return ResourceManager.GetString("resetPasswordInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid user information..
        /// </summary>
        public static string resetPswd_UserIdNotProvided {
            get {
                return ResourceManager.GetString("resetPswd_UserIdNotProvided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This reset password link has expired, please reset your password again..
        /// </summary>
        public static string resetPwdExpired {
            get {
                return ResourceManager.GetString("resetPwdExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error sending the password recovery email to: {0}.
        /// </summary>
        public static string sendMailError {
            get {
                return ResourceManager.GetString("sendMailError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password successfully updated..
        /// </summary>
        public static string success_ChangePswd {
            get {
                return ResourceManager.GetString("success_ChangePswd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This email address not exist..
        /// </summary>
        public static string Success_Email {
            get {
                return ResourceManager.GetString("Success_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        public static string titleChangePswd {
            get {
                return ResourceManager.GetString("titleChangePswd", resourceCulture);
            }
        }
    }
}
