//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SharedClass.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UserResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UserResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SharedClass.Resources.UserResource", typeof(UserResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New.
        /// </summary>
        public static string btn_AddNew {
            get {
                return ResourceManager.GetString("btn_AddNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forum Research.
        /// </summary>
        public static string displayName {
            get {
                return ResourceManager.GetString("displayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error trying to validate the email address. Please try again..
        /// </summary>
        public static string Error_DBEmailValidationError {
            get {
                return ResourceManager.GetString("Error_DBEmailValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to delete the user. Something went wrong when connecting to the database. Please try again. (EUA100).
        /// </summary>
        public static string Error_DeleteUser {
            get {
                return ResourceManager.GetString("Error_DeleteUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This email address is already used for another user. Please use a unique email address..
        /// </summary>
        public static string Error_EmailInUse {
            get {
                return ResourceManager.GetString("Error_EmailInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid email address..
        /// </summary>
        public static string Error_InvalidEmail {
            get {
                return ResourceManager.GetString("Error_InvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email must be between 4 and 150 characters..
        /// </summary>
        public static string Error_InvalidEmailLength {
            get {
                return ResourceManager.GetString("Error_InvalidEmailLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid user information..
        /// </summary>
        public static string Error_InvalidUser {
            get {
                return ResourceManager.GetString("Error_InvalidUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to add the user. Something went wrong when connecting to the database. Please try again. (EUA100).
        /// </summary>
        public static string Error_UnableToSaveUser {
            get {
                return ResourceManager.GetString("Error_UnableToSaveUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to update the user. Something went wrong when connecting to the database. Please try again. (EUA100).
        /// </summary>
        public static string Error_UnableToUpdateUser {
            get {
                return ResourceManager.GetString("Error_UnableToUpdateUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rgeorge@forumresearch.com.
        /// </summary>
        public static string fromAddress {
            get {
                return ResourceManager.GetString("fromAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We have created an account for the TARION ANALYTICS PORTAL. To access this site, simply click on the following link or paste it into your browser.
        ///
        ///{0}
        ///            
        ///Credentials:  Username-  {1}, Password-  {2}
        ///                                                                                                                                                                                                                                                                                                       
        ///Regard [rest of string was truncated]&quot;;.
        /// </summary>
        public static string mailContent {
            get {
                return ResourceManager.GetString("mailContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tarion Forum Created a new account.
        /// </summary>
        public static string mailSubject {
            get {
                return ResourceManager.GetString("mailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully added the user..
        /// </summary>
        public static string Message_AddSuccess {
            get {
                return ResourceManager.GetString("Message_AddSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully updated the user..
        /// </summary>
        public static string Message_UpdateSuccess {
            get {
                return ResourceManager.GetString("Message_UpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user deleted successfully..
        /// </summary>
        public static string Success_DeleteUser {
            get {
                return ResourceManager.GetString("Success_DeleteUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This email address is not associated with with existing user..
        /// </summary>
        public static string Success_Email {
            get {
                return ResourceManager.GetString("Success_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        public static string th_Action {
            get {
                return ResourceManager.GetString("th_Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string th_Email {
            get {
                return ResourceManager.GetString("th_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FullName.
        /// </summary>
        public static string th_FullName {
            get {
                return ResourceManager.GetString("th_FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group.
        /// </summary>
        public static string th_Group {
            get {
                return ResourceManager.GetString("th_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LastLogin.
        /// </summary>
        public static string th_LastLogin {
            get {
                return ResourceManager.GetString("th_LastLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string th_Status {
            get {
                return ResourceManager.GetString("th_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserID.
        /// </summary>
        public static string th_UserID {
            get {
                return ResourceManager.GetString("th_UserID", resourceCulture);
            }
        }
    }
}
